<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-13T16:04:08 IST" name="Default suite" finished-at="2024-12-13T16:05:21 IST" duration-ms="72760">
    <groups>
    </groups>
    <test started-at="2024-12-13T16:04:08 IST" name="Default test" finished-at="2024-12-13T16:05:21 IST" duration-ms="72760">
      <class name="test_class.reg_testclass">
        <test-method is-config="true" signature="setup()[pri:0, instance:test_class.reg_testclass@27462a88]" started-at="2024-12-13T16:04:08 IST" name="setup" finished-at="2024-12-13T16:04:36 IST" duration-ms="28011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="projecttest()[pri:0, instance:test_class.reg_testclass@27462a88]" started-at="2024-12-13T16:04:36 IST" name="projecttest" finished-at="2024-12-13T16:05:21 IST" duration-ms="44539" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Best Place to Buy Spices Online in India - Spice Munnar] but found [spice]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Best Place to Buy Spices Online in India - Spice Munnar] but found [spice]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at page_class.reg_pageclass.tab(reg_pageclass.java:193)
at test_class.reg_testclass.projecttest(reg_testclass.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- projecttest -->
      </class> <!-- test_class.reg_testclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
